var myNum = 10;
console.log(myNum);
var myStr = 'строка';
console.log(myStr);
var myBool=true;
console.log(myBool);
var myArr = [1,2,3,4,5];
console.log(myArr);
var decimal2 = myNum.toFixed;
var i =1;
console.log(++i);
console.log(i++);
console.log(--i);
console.log(i--);
var myTest = 20;
myTest+=myNum;
myTest-=myNum;
myTest*=myNum;
myTest/=myNum;
myTest%=myNum;
var myPi = Math.PI;
console.log(myPi);
var myRound = Math.round(89.279);
console.log(myRound);
var myRandom = Math.random()*10;
console.log(myRandom);
var myPow = Math.pow(3,5);
console.log(myPow);
var strObj = {str:'Мама мыла раму, рама мыла маму'};
strObj.length = strObj.str.length;
var isRamaPos = strObj.str.indexOf('рама');
console.log(isRamaPos);
var strReplace = strObj.str.replace('Мама мыла раму, рама мыла маму', 'Мама моет раму, Рама держит маму');
// 9. Преобразуйте любую строку в верхний, затем в нижний регистры,
// результат отобразите в консоли.
var str = strObj.str.toUpperCase();
console.log(str);
var str = strObj.str.toLowerCase();
console.log(str);  